version: "3"
services:

  node:
    build: ./frontend
    image: portfolio_node
    volumes:
      - ./frontend:/node
    ports:
      - "3000:3000"
    networks:
      - frontend
    container_name: portfolio_node

  nginx:
    build: ./nginx
    image: portfolio_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - frontend
    container_name: portfolio_nginx

networks:
  frontend:
